project/apps/lotto/urls.py
from django.conf.urls import patterns, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('project.apps.lotto.views',
    url(r'^$', 'index', name='index'),
    
    # user
    url(r'^register$', 'register', name='register'),
    url(r'^login$', 'user_login', name='login'),
    url(r'^logout$', 'user_logout', name='logout'),
    
    # tickets
    url(r'^ticket/create$', 'ticket_create', name='ticket_create'),
    url(r'^ticket/edit/(?P<ticket_id>\d+)/$', 'ticket_edit', name='ticket_edit'),
    url(r'^ticket/delete/(?P<ticket_id>\d+)/$', 'ticket_delete',
        name='ticket_delete'),
    url(r'^ticket/list$', 'ticket_list', name='ticket_list'),
    url(r'^ticket/list-upcoming$', 'ticket_list_upcoming',
        name='ticket_list_upcoming'),
    url(r'^ticket/check$', 'ticket_check', name='ticket_check'),
    
    #ajax
    url(r'^ticket/ajax/check$', 'ticket_ajax_check', name='ticket_ajax_check'),
    
) + staticfiles_urlpatterns()

project/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('project.apps.lotto.urls', namespace="lotto")),
]

project/apps/lotto/models.py
from django.db import models
from django.contrib.auth.models import User

from datetime import datetime

from project.lib import mail


class Ticket(models.Model):
    ''' Model for storing lottery ticket data. '''
    
    class Meta:
        ordering = ['-date', 'n1', 'n2', 'n3', 'n4', 'n5', 'n6']
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, blank=False, null=False,
        verbose_name="User", db_index=True)
    
    n1 = models.IntegerField('Number-1', blank=False, null=False)
    n2 = models.IntegerField('Number-2', blank=False, null=False)
    n3 = models.IntegerField('Number-3', blank=False, null=False)
    n4 = models.IntegerField('Number-4', blank=False, null=False)
    n5 = models.IntegerField('Number-5', blank=False, null=False)
    n6 = models.IntegerField('Number-6', blank=False, null=False)
    win = models.IntegerField('Win', blank=True, default=0)
    checked = models.BooleanField('Checked', blank=True, default=False)
    date = models.DateField()
    
    
    def check_numbers(self, win_numbers):
        ''' Checks if this thickets the same numbers as in the win_numbers
            list. If it does then it will send email to the user. It will also
            update itself for checked and win attributes.
            
            Note: all number should be integers, no strings allowed.
        '''
        self.checked = True
        self.win = 0
        win_count = 0
        for i in range(6):
            # getting n1, n2, etc. attribute of self
            n = getattr(self, 'n%d' % (i+1)) 
            if n in win_numbers:
                win_count += 1
        
        if win_count < 3:
            self.save()
            return
        
        self.win = win_count
        self.save()
        
        if self.user.email:
            try:
                mail.send(self.user.email, 'You have a winning ticket',
                    'Your ticket #%d (for date: %s) has won!' % \
                            (self.id, self.date))
            except:
                pass
    
    
    def is_outdated(self):
        return self.date < datetime.now().date()
    
    def is_today(self):
        return self.date == datetime.now().date()
    
    def __str__(self):
        return 'Ticket #%06d (date: %s)' % (self.id, str(self.date))
    
        
    

project/apps/lotto/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from .models import Ticket

class TicketForm(forms.ModelForm):
    ''' Model for ticket data. '''
    
    class Meta:
        model = Ticket
        # fields that will be in the form
        fields = ['date', 'n1', 'n2', 'n3', 'n4', 'n5', 'n6']
        
        

class UserCreateForm(UserCreationForm):
    ''' We extend default Django form for registration and add an email field to
        it.
    '''
    email = forms.EmailField(required=False)
    
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        # saving user with email
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

project/apps/lotto/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required

from project.lib import mail
from datetime import datetime
from .forms import TicketForm, UserCreateForm
from .models import Ticket
from project.apps.lotto.utils import tickets as tickets_util


def index(request):
    return render(request, 'lotto/index.html', {})


def register(request):
    # if already logged in just redirect to the main page
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('lotto:index'))
    
    if request.method == 'POST':
        form = UserCreateForm(request.POST)
        if form.is_valid():
            form.save() # creates new records in the DB
            # authenticating user
            username = request.POST['username']
            password = request.POST['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.add_message(request, messages.SUCCESS,
                'Successful regisration.')
            if user.email:
                # can be some error that we don't what to handle
                # (like email is not an email)
                try: 
                    mail.send(user.email, 'Registrierung bei Lottochecker.',
                        'Sie wurden bei Lottochecker registriert..')
                except:
                    pass
            return HttpResponseRedirect(reverse('lotto:index'))
    else:
        form = UserCreateForm()
            
    return render(request, 'form-page.html', {
        'form': form,
        'form_title': 'Register',
    })


def user_login(request):
    # if already logged in just redirect to the main page
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('lotto:index'))
    
    if request.method == 'POST':
        form = AuthenticationForm(None, request.POST)
        # if login and password are correct
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']

            user = authenticate(username=username, password=password)
            login(request, user)
            
            if user.email:
                # can be some error that we don't what to handle
                # (like email is not an email)
                try: 
                    mail.send(user.email, 'Anmeldung bei Lottochecker.',
                        'Ein Login wurde bei Lottochecker mit Ihrem'
                                'Konto durchgefuehrt.')
                except:
                    pass
            
            messages.add_message(request, messages.SUCCESS, 'Angemeldet')
            return HttpResponseRedirect(reverse('lotto:ticket_list_upcoming'))
        else:
            pass
            #messages.add_message(request, messages.ERROR,
            #    'Authentication failure.')
    else:
        form = AuthenticationForm()
    
    
    return render(request, 'form-page.html', {
        'form': form,
        'form_title': 'Anmeldung',
    })


def user_logout(request):
    # if not logged in just redirect to the main page
    if request.user.is_authenticated():
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'Abgemeldet')
    return HttpResponseRedirect(reverse('lotto:index'))


@login_required
def ticket_create(request):
    if request.method == 'POST':
        form = TicketForm(request.POST)
        if form.is_valid():
            ticket = form.instance
            ticket.user = request.user
            ticket.save()
            messages.add_message(request, messages.SUCCESS,
                'Neuer Schein erstellt')
            return HttpResponseRedirect(reverse('lotto:ticket_list'))
        else:
            pass
            #messages.add_message(request, messages.ERROR,
            #    'Authentication failure.')
    else:
        form = TicketForm()
        
    return render(request, 'form-page.html', {
        'form_title': 'Neuen Schein erstellen',
        'form': form,
        'form_text': 'Bitte geben Sie Ziehungsdatum und Tippzahlen ein:'
    })


@login_required
def ticket_edit(request, ticket_id):
    ticket = get_object_or_404(Ticket, user=request.user, id=ticket_id,
        date__gte=datetime.now().date())
    if request.method == 'POST':
        form = TicketForm(request.POST, instance=ticket)
        #raise Exception(form.instance)
        if form.is_valid():
            ticket = form.instance
            ticket.user = request.user
            ticket.save()
            messages.add_message(request, messages.SUCCESS,
                'Changes saved.')
            return HttpResponseRedirect(reverse('lotto:ticket_list'))
    else:
        form = TicketForm(instance=ticket)
    
    return render(request, 'form-page.html', {
        'form_title': 'Ticket Edit ',
        'form': form,
        'submit_text': 'Save changes',
    })
    
@login_required
def ticket_delete(request, ticket_id):
    ticket = get_object_or_404(Ticket, user=request.user, id=ticket_id)
    ticket_id = ticket.id # will be set to None after delete
    ticket.delete()
    messages.add_message(request, messages.SUCCESS,
        'Ticket #%s (for date: %s) deleted.' % (ticket_id, ticket.date))
    # redirect to previous page
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    

@login_required
def ticket_list(request, upcoming=False):
    tickets = Ticket.objects.filter(user=request.user)
    if upcoming:
        tickets = tickets.filter(date__gte=datetime.now().date())
    
    return render(request, 'lotto/ticket/list-page.html', {
        'tickets': tickets,
        'upcoming': upcoming,
    })
    
@login_required    
def ticket_list_upcoming(request):
    return ticket_list(request, upcoming=True)


@login_required
def ticket_check(request):
    ''' Just calls ticket_check function, used for for debugging purposes. '''
    tickets_util.check_tickets()
    messages.add_message(request, messages.INFO, 'Tickets checked.')
    return ticket_list(request)


@login_required
def ticket_ajax_check(request):
    ''' Checking tickets with ajax '''
    win_tickets = tickets_util.check_tickets()
    user_wins = [t for t in win_tickets if t.user.id == request.user.id]
    
    upcoming = request.GET.get('upcoming', 'false') != 'false'
    
    tickets = Ticket.objects.filter(user=request.user)
    if upcoming:
        tickets = tickets.filter(date__gte=datetime.now().date())
        
    return render(request, 'lotto/ticket/list-snippet.html', {
        'tickets': tickets,
        'upcoming': upcoming,
        'ajax': True,
        'win_tickets': len(win_tickets),
        'user_wins': len(user_wins),
    });
    

project/templates/form-page.html
{% extends 'layout.html' %}

{% block title %}
	{{ block.super }} |
	{% if form_title %}
		{{ form_title  }}
	{% else %}
		{{ page_title  }}
	{% endif %}
{% endblock %}


{% block content %}
	<div class="col-md-8 col-md-offset-2">
		<h1>{{ form_title }}</h1>
		
		{% if form_text %}
			<p class="form-text">{{ form_text }}</p>
			<hr>
		{% endif %}
		
		<form method="POST" role="form" autocomplete="off">{% csrf_token %}
			{% include 'form-snippet.html' %}
		</form>
	<br><br><br><br>
	</div>
	
{% endblock %}

project/templates/form-snippet.html
{% load form_filters %}

<!-- The text and password here are to prevent FF from auto filling my login credentials because it ignores autocomplete="off"-->
<input type="text" style="display:none">
<input type="password" style="display:none">

{# Include the hidden fields #}
{% for hidden in form.hidden_fields %}
	{% csrf_token %}
	{{ hidden }}
{% endfor %}

{# Include the visible fields #}


{% if form.errors %}
	{% if form.non_field_errors %}
		<p class="error">Form has errors:</p>
		{{ form.non_field_errors }}
	{% else %}
		<p  class="error">Form has errors.</p>
	{% endif %}
	<br>
{% endif %}


{% for field in form.visible_fields %}
	<div class="form-group {% if field.errors %} has-error {% endif %}">
    	<label class="control-label {% if field.field.required %}required{% endif %}"
    		for="id_{{ field.name }}">{{ field.label }}:</label>
    	
    	{% if field.errors %}
		<div class="form-errors">
    		{{ field.errors }}
		</div>
    	{% endif %}
    	<input type="{{  field|html_fieldtype }}" class="form-control"
    		id="id_{{ field.name }}" name="{{ field.name }}"
    		{% if field.value %}
    			{% if field|html_fieldtype != 'date' %}
    				value="{{ field.value }}"
				{% else %}
					value="{{ field.value|date:'c' }}"
    			{% endif %}
    		{% endif %}">

    	{% if field.help_text %}
    		<p class="help-text">{{ field.help_text }}</p>
		{% endif %}
    </div>
{% endfor %}

<br>
<div class="text-right">
	<button type="submit" class="btn btn-primary">
		{% if submit_text %}
			{{ submit_text }}
		{% else %}
			Submit
		{% endif %}
	</button>
</div>

project/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<title>{% block title %}Lottochecker{% endblock %}</title>
		<meta charset="utf-8" />
		
		{% block style %}
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap/bootstrap.min.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap/bootstrap-theme.min.css' %}" />
		
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
		{% endblock %}
		
		{% block js %}
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		
		<script src="{% static 'js/fixes.js' %}"></script>
		{% endblock %}
	</head>
<body>
	<nav class="navbar navbar-default navbar-static-top">
	    <div class="container-fluid">
	        <!-- Brand and toggle get grouped for better mobile display -->
	        <div class="navbar-header">
	            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	                <span class="sr-only">Toggle navigation</span>
	                <span class="icon-bar"></span>
	                <span class="icon-bar"></span>
	                <span class="icon-bar"></span>
	            </button>
	            <a class="navbar-brand" href="/">Lottochecker</a>
	        </div>
	
	        <!-- Collect the nav links, forms, and other content for toggling -->
	        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	            <ul class="nav navbar-nav">
	                <li><a href="/">Start</a></li>
	                	<!-- Action menu -->
		                <li class="dropdown">
	                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Aktion<span class="caret"></span></a>
	                    <ul class="dropdown-menu">
	                    	{% if request.user.is_authenticated %}
		                        <li><a href="{% url 'lotto:ticket_create' %}">Neuen Lottoschein anlegen</a></li>
		                        <li role="separator" class="divider"></li>
		                        <li><a href="{% url 'lotto:ticket_list_upcoming' %}">Zeige offene Lottoscheine</a></li>
		                        <li><a href="{% url 'lotto:ticket_list' %}">Zeige alle Lottoscheine</a></li>
	                        {% else %}
	                        	<li class="disabled"><a href="#">Nicht verfügbar</a></li>
	                        {% endif %}
	                    </ul>
	                </li>
	            </ul>
	            
	            <ul class="nav navbar-nav navbar-right">
	                <li><p class="navbar-text" title="Logged in as:...">Angemeldet als:
	                	<strong>
	                	{% if request.user.is_authenticated %}
	                		{{ request.user.username }}
                		{% else %}
                			Gast
            			{% endif %}
                		</strong>
                	</p></li>
	                <li class="dropdown">
	                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
	                    <ul class="dropdown-menu">
	                    	{% if request.user.is_authenticated %}
	                    		<li><a href="{% url 'lotto:logout' %}">Abmelden</a></li>
	                    	{% else %}
		                        <li><a href="{% url 'lotto:login' %}">Anmelden</a></li>
		                        <li role="separator" class="divider"></li>
		                        <li><a href="{% url 'lotto:register' %}">Registrieren</a></li>
	                        {% endif %}
	                    </ul>
	                </li>
	            </ul>
	        </div><!-- /.navbar-collapse -->
	    </div><!-- /.container-fluid -->
	</nav>
	
	<div class="container">
	
	{% if messages %}
	    {% for message in messages %}
	    <div class="alert alert-{% if message.tags != 'error' %}{{ message.tags }}{% else %}danger{% endif %}" role="alert">{{ message }}</div>
	    {% endfor %}
	{% endif %}
	
	
	{% block content %}
	{% endblock %}
	</div>
</body>
</html>