project/apps/lotto/urls.py
from django.conf.urls import patterns, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns('project.apps.lotto.views',
    url(r'^$', 'index', name='index'),
    
    # user
    url(r'^register$', 'register', name='register'),
    url(r'^login$', 'user_login', name='login'),
    url(r'^logout$', 'user_logout', name='logout'),
    
    # tickets
    url(r'^ticket/create$', 'ticket_create', name='ticket_create'),
    url(r'^ticket/edit/(?P<ticket_id>\d+)/$', 'ticket_edit', name='ticket_edit'),
    url(r'^ticket/delete/(?P<ticket_id>\d+)/$', 'ticket_delete',
        name='ticket_delete'),
    url(r'^ticket/list$', 'ticket_list', name='ticket_list'),
    url(r'^ticket/list-upcoming$', 'ticket_list_upcoming',
        name='ticket_list_upcoming'),
    url(r'^ticket/check$', 'ticket_check', name='ticket_check'),
    
    #ajax
    url(r'^ticket/ajax/check$', 'ticket_ajax_check', name='ticket_ajax_check'),
    
) + staticfiles_urlpatterns()

project/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('project.apps.lotto.urls', namespace="lotto")),
]

project/apps/lotto/models.py
from django.db import models
from django.contrib.auth.models import User

from datetime import datetime

from project.lib import mail


class Ticket(models.Model):
    ''' Model for storing lottery ticket data. '''
    
    class Meta:
        ordering = ['-date', 'n1', 'n2', 'n3', 'n4', 'n5', 'n6']
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, blank=False, null=False,
        verbose_name="User", db_index=True)
    
    n1 = models.IntegerField('Number-1', blank=False, null=False)
    n2 = models.IntegerField('Number-2', blank=False, null=False)
    n3 = models.IntegerField('Number-3', blank=False, null=False)
    n4 = models.IntegerField('Number-4', blank=False, null=False)
    n5 = models.IntegerField('Number-5', blank=False, null=False)
    n6 = models.IntegerField('Number-6', blank=False, null=False)
    win = models.IntegerField('Win', blank=True, default=0)
    checked = models.BooleanField('Checked', blank=True, default=False)
    date = models.DateField()
    
    
    def check_numbers(self, win_numbers):
        ''' Checks if this thickets the same numbers as in the win_numbers
            list. If it does then it will send email to the user. It will also
            update itself for checked and win attributes.
            
            Note: all number should be integers, no strings allowed.
        '''
        self.checked = True
        self.win = 0
        win_count = 0
        for i in range(6):
            # getting n1, n2, etc. attribute of self
            n = getattr(self, 'n%d' % (i+1)) 
            if n in win_numbers:
                win_count += 1
        
        if win_count < 3:
            self.save()
            return
        
        self.win = win_count
        self.save()
        
        if self.user.email:
            try:
                mail.send(self.user.email, 'You have a winning ticket',
                    'Your ticket #%d (for date: %s) has won!' % \
                            (self.id, self.date))
            except:
                pass
    
    
    def is_outdated(self):
        return self.date < datetime.now().date()
    
    def is_today(self):
        return self.date == datetime.now().date()
    
    def __str__(self):
        return 'Ticket #%06d (date: %s)' % (self.id, str(self.date))
    
        
    

project/apps/lotto/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from .models import Ticket

class TicketForm(forms.ModelForm):
    ''' Model for ticket data. '''
    
    class Meta:
        model = Ticket
        # fields that will be in the form
        fields = ['date', 'n1', 'n2', 'n3', 'n4', 'n5', 'n6']
        
        

class UserCreateForm(UserCreationForm):
    ''' We extend default Django form for registration and add an email field to
        it.
    '''
    email = forms.EmailField(required=False)
    
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        # saving user with email
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

project/apps/lotto/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required

from project.lib import mail
from datetime import datetime
from .forms import TicketForm, UserCreateForm
from .models import Ticket
from project.apps.lotto.utils import tickets as tickets_util


def index(request):
    return render(request, 'lotto/index.html', {})


def register(request):
    # if already logged in just redirect to the main page
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('lotto:index'))
    
    if request.method == 'POST':
        form = UserCreateForm(request.POST)
        if form.is_valid():
            form.save() # creates new records in the DB
            # authenticating user
            username = request.POST['username']
            password = request.POST['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.add_message(request, messages.SUCCESS,
                'Successful regisration.')
            if user.email:
                # can be some error that we don't what to handle
                # (like email is not an email)
                try: 
                    mail.send(user.email, 'Registrierung bei Lottochecker.',
                        'Sie wurden bei Lottochecker registriert..')
                except:
                    pass
            return HttpResponseRedirect(reverse('lotto:index'))
    else:
        form = UserCreateForm()
            
    return render(request, 'form-page.html', {
        'form': form,
        'form_title': 'Register',
    })


def user_login(request):
    # if already logged in just redirect to the main page
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('lotto:index'))
    
    if request.method == 'POST':
        form = AuthenticationForm(None, request.POST)
        # if login and password are correct
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']

            user = authenticate(username=username, password=password)
            login(request, user)
            
            if user.email:
                # can be some error that we don't what to handle
                # (like email is not an email)
                try: 
                    mail.send(user.email, 'Anmeldung bei Lottochecker.',
                        'Ein Login wurde bei Lottochecker mit Ihrem'
                                'Konto durchgefuehrt.')
                except:
                    pass
            
            messages.add_message(request, messages.SUCCESS, 'Angemeldet')
            return HttpResponseRedirect(reverse('lotto:ticket_list_upcoming'))
        else:
            pass
            #messages.add_message(request, messages.ERROR,
            #    'Authentication failure.')
    else:
        form = AuthenticationForm()
    
    
    return render(request, 'form-page.html', {
        'form': form,
        'form_title': 'Anmeldung',
    })


def user_logout(request):
    # if not logged in just redirect to the main page
    if request.user.is_authenticated():
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'Abgemeldet')
    return HttpResponseRedirect(reverse('lotto:index'))


@login_required
def ticket_create(request):
    if request.method == 'POST':
        form = TicketForm(request.POST)
        if form.is_valid():
            ticket = form.instance
            ticket.user = request.user
            ticket.save()
            messages.add_message(request, messages.SUCCESS,
                'Neuer Schein erstellt')
            return HttpResponseRedirect(reverse('lotto:ticket_list'))
        else:
            pass
            #messages.add_message(request, messages.ERROR,
            #    'Authentication failure.')
    else:
        form = TicketForm()
        
    return render(request, 'form-page.html', {
        'form_title': 'Neuen Schein erstellen',
        'form': form,
        'form_text': 'Bitte geben Sie Ziehungsdatum und Tippzahlen ein:'
    })


@login_required
def ticket_edit(request, ticket_id):
    ticket = get_object_or_404(Ticket, user=request.user, id=ticket_id,
        date__gte=datetime.now().date())
    if request.method == 'POST':
        form = TicketForm(request.POST, instance=ticket)
        #raise Exception(form.instance)
        if form.is_valid():
            ticket = form.instance
            ticket.user = request.user
            ticket.save()
            messages.add_message(request, messages.SUCCESS,
                'Changes saved.')
            return HttpResponseRedirect(reverse('lotto:ticket_list'))
    else:
        form = TicketForm(instance=ticket)
    
    return render(request, 'form-page.html', {
        'form_title': 'Ticket Edit ',
        'form': form,
        'submit_text': 'Save changes',
    })
    
@login_required
def ticket_delete(request, ticket_id):
    ticket = get_object_or_404(Ticket, user=request.user, id=ticket_id)
    ticket_id = ticket.id # will be set to None after delete
    ticket.delete()
    messages.add_message(request, messages.SUCCESS,
        'Ticket #%s (for date: %s) deleted.' % (ticket_id, ticket.date))
    # redirect to previous page
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    

@login_required
def ticket_list(request, upcoming=False):
    tickets = Ticket.objects.filter(user=request.user)
    if upcoming:
        tickets = tickets.filter(date__gte=datetime.now().date())
    
    return render(request, 'lotto/ticket/list-page.html', {
        'tickets': tickets,
        'upcoming': upcoming,
    })
    
@login_required    
def ticket_list_upcoming(request):
    return ticket_list(request, upcoming=True)


@login_required
def ticket_check(request):
    ''' Just calls ticket_check function, used for for debugging purposes. '''
    tickets_util.check_tickets()
    messages.add_message(request, messages.INFO, 'Tickets checked.')
    return ticket_list(request)


@login_required
def ticket_ajax_check(request):
    ''' Checking tickets with ajax '''
    win_tickets = tickets_util.check_tickets()
    user_wins = [t for t in win_tickets if t.user.id == request.user.id]
    
    upcoming = request.GET.get('upcoming', 'false') != 'false'
    
    tickets = Ticket.objects.filter(user=request.user)
    if upcoming:
        tickets = tickets.filter(date__gte=datetime.now().date())
        
    return render(request, 'lotto/ticket/list-snippet.html', {
        'tickets': tickets,
        'upcoming': upcoming,
        'ajax': True,
        'win_tickets': len(win_tickets),
        'user_wins': len(user_wins),
    });
    

project/templates/lotto/ticket/list-page.html
{% extends 'layout.html' %}

{% block title %}
	{{ block.super }} |
	{% if upcoming %}
		Offene Scheine
	{% else %}
		Gesamtliste
	{% endif %}
{% endblock %}


{% block js %}
	{{ block.super }}
	<script src="/static/lotto/js/list-page.js"></script>
	<script>
		var upcoming = {% if upcoming %}true{% else %}false{% endif %};
	</script>
{% endblock %}


{% block content %}

{% if upcoming %}
	<h1>Offene Scheine</h1>
	<p>Liste offener Lottoscheine.</p>
{% else %}
	<h1>Gesamtliste</h1>
	<p>Liste aller Lottoscheine.</p>
{% endif %}
<br>

<div class="col-md-10 col-md-offset-1">
	<div id="ticket-list-wrapper">
		{% include 'lotto/ticket/list-snippet.html' %}
	</div>
	
	<br>
	<div class="text-right">
		<input type="button" value="Jetzt überprüfen" class="btn btn-success"
			id="check-tickets">
	</div>
</div>
{% endblock %}

project/templates/lotto/ticket/list-snippet.html
{% if ajax %}
	<strong>Lottoscheine wurden überprüft:</strong>
	<!--<ul>
		<li>Your winning tickets: {{ user_wins }}</li>
		<li>Anzahl Lottoschein mit Gewinn: {{ win_tickets }}</li>
	</ul>-->
	<br>
{% endif %}

<table class="table table-hover">
	<thead>
		<tr>
			<th class="text-center">
				<span class="glyphicon glyphicon-ok" title="Anzahl der Gewinnzahlen"></span>
			</th>
			<th class="text-center">Ziehung</th>
			<th class="text-center">N-1</th>
			<th class="text-center">N-2</th>
			<th class="text-center">N-3</th>
			<th class="text-center">N-4</th>
			<th class="text-center">N-5</th>
			<th class="text-center">N-6</th>
			<th class="text-center">Aktion</th>
		</tr>
	</thead>
	<tbody>
	{% for ticket in tickets %}
		<tr class="text-center
			{% if ticket.win %}
				success
			{% endif %}
			{% if ticket.is_outdated %}
				disabled-text
			{% endif %}
			{% if ticket.is_today %}bold{% endif %}
		">
			<td>
				{% if ticket.win %}
					{{ ticket.win }}
				{% elif ticket.checked %}
					<span class="glyphicon glyphicon-remove"></span>
				{% endif %}
			</td>
			<td>{{ ticket.date }}</td>
			<td class="text-center">{{ ticket.n1 }}</td>
			<td>{{ ticket.n2 }}</td>
			<td>{{ ticket.n3 }}</td>
			<td>{{ ticket.n4 }}</td>
			<td>{{ ticket.n5 }}</td>
			<td>{{ ticket.n6 }}</td>
			<td>
				<a href="{% url 'lotto:ticket_delete' ticket.id %}"
					><span class="glyphicon glyphicon-remove glyphicon-delete-command" title="Löschen"></span></a>
				{% if not ticket.is_outdated %}
					&nbsp;
					<a href="{% url 'lotto:ticket_edit' ticket.id %}"
						><span class="glyphicon glyphicon-pencil glyphicon-edit-command" title="Ändern"></span></a>
				{% endif %}
			</td>
		<tr>
	{% empty %}
		<tr class="text-center">
			<td colspan="9">
				Nichts anzuzeigen.
			</td>
		<tr>
	{% endfor %}
	</tbody>
</table>

project/templates/lotto/ticket/list.html
{% extends 'layout.html' %}

{% block title %}
	{{ block.super }} |
	{% if upcoming %}
		Upcoming Tickets
	{% else %}
		Ticket List
	{% endif %}
{% endblock %}

{% block content %}

{% if upcoming %}
	<h1>Upcoming Tickets</h1>
	<p>List of upcoming tickets.</p>
{% else %}
	<h1>Ticket List</h1>
	<p>List of all tickets.</p>
{% endif %}
<br>

<div class="col-md-10 col-md-offset-1">
	<table class="table table-hover">
		<thead>
			<tr>
				<th class="text-center">
					<span class="glyphicon glyphicon-ok" title="Count of winning numbers"></span>
				</th>
				<th class="text-center">Date</th>
				<th class="text-center">N-1</th>
				<th class="text-center">N-2</th>
				<th class="text-center">N-3</th>
				<th class="text-center">N-4</th>
				<th class="text-center">N-5</th>
				<th class="text-center">N-6</th>
				<th class="text-center">Command</th>
			</tr>
		</thead>
		<tbody>
		{% for ticket in tickets %}
			<tr class="text-center
				{% if ticket.win %}
					success
				{% endif %}
				{% if ticket.is_outdated %}
					disabled-text
				{% endif %}
				{% if ticket.is_today %}bold{% endif %}
			">
				<td>
					{% if ticket.win %}
						{{ ticket.win }}
					{% elif ticket.checked %}
						<span class="glyphicon glyphicon-remove"></span>
					{% endif %}
				</td>
				<td>{{ ticket.date }}</td>
				<td class="text-center">{{ ticket.n1 }}</td>
				<td>{{ ticket.n2 }}</td>
				<td>{{ ticket.n3 }}</td>
				<td>{{ ticket.n4 }}</td>
				<td>{{ ticket.n5 }}</td>
				<td>{{ ticket.n6 }}</td>
				<td>
					<a href="{% url 'lotto:ticket_delete' ticket.id %}"
						><span class="glyphicon glyphicon-remove glyphicon-delete-command" title="Delete"></span></a>
					{% if not ticket.is_outdated %}
						&nbsp;
						<a href="{% url 'lotto:ticket_edit' ticket.id %}"
							><span class="glyphicon glyphicon-pencil glyphicon-edit-command" title="Edit"></span></a>
					{% endif %}
				</td>
			<tr>
		{% empty %}
			<tr class="text-center">
				<td colspan="9">
					No tickets to display.
				</td>
			<tr>
		{% endfor %}
		</tbody>
	</table>
</div>
{% endblock %}